"""Assemble a self-contained deploy folder for Plotly Cloud.

Plotly Cloud has no runtime volume mounts, so the app's precomputed data must
ship *inside* the uploaded folder -- while the repo itself stays data-free. This
script builds a staging folder that combines the code and the data:

    <deploy>/
        app.py                 # entrypoint: points the app at the bundled data
        pyproject.toml         # runtime-only deps (no umap/precompute stack)
        .python-version        # pin Python for the Cloud build
        .gitignore             # ignores envs/caches, but NOT the data
        spotify_tracks_app/    # the app package (copied from src/)
        bundled_data/
            umap.parquet
            numeric_features.json

The staging folder is created OUTSIDE the repo so no data ever lands in it.
Publish it with the Plotly Cloud CLI (``pip install plotly-cloud``), the
``dash[cloud]`` dev-tools panel, or by uploading it at https://cloud.plotly.com.

Usage:
    uv run python scripts/deploy_prep.py [output_dir]
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

from spotify_tracks_app import config

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC_PACKAGE = _REPO_ROOT / "src" / "spotify_tracks_app"
_DEFAULT_OUTPUT = _REPO_ROOT.parent / "spotify-tracks-web-app-deploy"
_REPO_CLOUD_CONFIG = _REPO_ROOT / "plotly-cloud.toml"

# Runtime dependencies, declared in a pyproject.toml so Plotly Cloud's uv-based
# runtime (`uv run`) has a project environment to resolve -- a bare
# requirements.txt leaves `uv run` with no environment, so even gunicorn (which
# Plotly Cloud uses to serve the app) is missing at runtime. The umap /
# scikit-learn / numba stack and kagglehub are deliberately excluded: they are
# only needed for the offline precompute, not to serve the precomputed parquet.
# `package = false` tells uv this is a plain app directory, not an installable
# package, so uv installs the dependencies without trying to build it.
_PYPROJECT = """\
[project]
name = "spotify-tracks-app"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dash>=2.17",
    "plotly>=5.22",
    "pandas>=2.2",
    "numpy>=1.26,<2.3",
    "scipy>=1.13",
    "pyarrow>=16.0",
    "gunicorn>=22.0",
    "flask-compress>=1.15",
]

[tool.uv]
package = false
"""

# Entrypoint Plotly Cloud runs. It points SPOTIFY_DATA_DIR at the data bundled
# next to this file (an absolute, cwd-independent path) before importing the
# app, then exposes `app` and `server` for the platform to serve.
_APP_ENTRYPOINT = '''\
"""Plotly Cloud entrypoint (auto-generated by scripts/deploy_prep.py)."""

import os
from pathlib import Path

os.environ.setdefault(
    "SPOTIFY_DATA_DIR", str(Path(__file__).resolve().parent / "bundled_data")
)

from spotify_tracks_app.app import app, server  # noqa: E402,F401

if __name__ == "__main__":
    app.run(debug=True)
'''

# Ignore local envs/caches during upload, but never the bundled data.
_GITIGNORE = """\
.venv/
__pycache__/
*.pyc
.pytest_cache/
.ruff_cache/
"""


def _require_precomputed() -> None:
    """Ensure the precomputed artefacts exist before packaging.

    Raises:
        FileNotFoundError: If either artefact is missing.
    """
    for path in (config.UMAP_PARQUET, config.NUMERIC_FEATURES_JSON):
        if not path.is_file():
            raise FileNotFoundError(
                f"Missing {path}. Run `uv run python scripts/precompute.py` first."
            )


def _dir_size_mib(path: Path) -> float:
    """Return the total size of a directory tree in MiB.

    Args:
        path: Directory to measure.

    Returns:
        Size in MiB.
    """
    total = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
    return total / (1024 * 1024)


def build_deploy_folder(output_dir: Path) -> None:
    """Build the Plotly Cloud deploy folder at ``output_dir``.

    Args:
        output_dir: Destination folder (created fresh; replaced if it exists).
    """
    _require_precomputed()

    # Preserve the Plotly Cloud app binding across rebuilds. If the deploy
    # folder doesn't have one yet, seed it from the canonical repo config.
    cloud_config = output_dir / "plotly-cloud.toml"
    saved_cloud_config = None
    if cloud_config.is_file():
        saved_cloud_config = cloud_config.read_text()
    elif _REPO_CLOUD_CONFIG.is_file():
        saved_cloud_config = _REPO_CLOUD_CONFIG.read_text()

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    # Copy the app package.
    shutil.copytree(
        _SRC_PACKAGE,
        output_dir / "spotify_tracks_app",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )

    # Bundle the data.
    data_dir = output_dir / "bundled_data"
    data_dir.mkdir()
    shutil.copy2(config.UMAP_PARQUET, data_dir / config.UMAP_PARQUET.name)
    shutil.copy2(
        config.NUMERIC_FEATURES_JSON, data_dir / config.NUMERIC_FEATURES_JSON.name
    )

    # Write the deploy files.
    (output_dir / "app.py").write_text(_APP_ENTRYPOINT)
    (output_dir / "pyproject.toml").write_text(_PYPROJECT)
    (output_dir / ".python-version").write_text("3.12\n")
    (output_dir / ".gitignore").write_text(_GITIGNORE)

    # Restore the preserved Plotly Cloud app binding, if there was one.
    if saved_cloud_config is not None:
        cloud_config.write_text(saved_cloud_config)

    size = _dir_size_mib(output_dir)
    print(f"Deploy folder ready: {output_dir}")
    print(f"Total size: {size:.1f} MiB")
    if size > 80:
        print(
            "WARNING: > 80 MiB -- exceeds the direct-upload limit at "
            "cloud.plotly.com."
        )
    print("\nNext steps:")
    print(f"  cd {output_dir}")
    print("  pip install plotly-cloud   # provides the `plotly` CLI")
    print("  plotly user login          # authenticate (OAuth in browser)")
    print("  plotly app publish         # publish to Plotly Cloud")


def main() -> None:
    """Entrypoint: build the deploy folder from an optional CLI path."""
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_OUTPUT
    build_deploy_folder(output_dir.resolve())


if __name__ == "__main__":
    main()
